# completions-for — generate fish completions for any CLI that can emit them.
#
#   completions-for <tool>...          generate (skips fresh caches)
#   completions-for --force <tool>...  regenerate even if the cache is fresh
#   completions-for --list             show cached completions and their source
#
# Most modern CLIs can print their own fish completions, but each picks a
# different spelling (rustup: `completions fish`, docker: `completion fish`,
# gh: `completion -s fish`, ...). This probes the common spellings in order
# and caches the first output that looks like a completion script into
# $dotfish_completions_cache, which 95-completions.fish puts on
# $fish_complete_path. Quiet mode (-q) is for the startup refresh: missing
# tools and probe failures are skipped silently.
function completions-for --description 'Generate fish completions for any CLI that emits them'
    argparse f/force q/quiet l/list -- $argv; or return 2

    set -l cache $dotfish_completions_cache
    test -n "$cache"; or set cache ~/.cache/fish/dotfish-completions

    if set -q _flag_list
        for file in $cache/*.fish
            set -l first (head -n1 $file)
            set -l src (string replace -r '^# generated by completions-for from `(.*)`.*' '$1' -- $first)
            printf '%s\t%s\n' (string replace -r '\.fish$' '' -- (path basename $file)) $src
        end
        return 0
    end

    if test (count $argv) -eq 0
        echo 'usage: completions-for [--force] <tool>...' >&2
        return 2
    end

    # Spellings tried in order; first script-looking output wins.
    set -l probes \
        'completions fish' \
        'completion fish' \
        'completion -s fish' \
        'completions --shell fish' \
        '--completions fish'

    mkdir -p $cache; or return 1
    set -l failed 0

    for tool in $argv
        set -l bin (command -v $tool)
        if test -z "$bin"
            set -q _flag_quiet; or echo "completions-for: $tool: not installed" >&2
            set failed 1
            continue
        end

        # Fresh cache (newer than the binary) → nothing to do.
        set -l dest $cache/$tool.fish
        if not set -q _flag_force; and test -e $dest; and not test $bin -nt $dest
            continue
        end

        set -l done 0
        for probe in $probes
            set -l out (command $tool (string split ' ' -- $probe) 2>/dev/null)
            test $status -eq 0; or continue
            # Some tools exit 0 with usage text, or ignore the shell arg and
            # emit bash (gh: `completion fish` → bash script). Fish completions
            # always bind a command via -c/--command; bash's `complete -F` and
            # zsh/powershell output don't, so this filters all of those.
            string match -rq '^\s*complete\s+(\S+\s+)*(-c|--command)[ =]' -- $out; or continue

            set -l tmp $dest.tmp
            printf '# generated by completions-for from `%s %s` — do not edit\n' $tool $probe >$tmp
            printf '%s\n' $out >>$tmp
            mv $tmp $dest
            set -q _flag_quiet; or echo "completions-for: $tool ← `$tool $probe`"
            set done 1
            break
        end

        if test $done -eq 0
            set -q _flag_quiet; or echo "completions-for: $tool: no completion generator found" >&2
            set failed 1
        end
    end

    return $failed
end
