// Package agentskill publishes the installed Modules' usage guides as context
// for AI coding agents (`dotfish agent`). Coding agents otherwise re-discover
// on every session what this shell's aliases and Wrappers do by poking at
// ~/.config/fish; writing the same guides the docs carry, scoped to the
// Modules actually installed, answers that once per machine.
//
// Two provider formats are supported:
//   - claude: a Claude Code agent skill at ~/.claude/skills/dotfish/SKILL.md.
//     dotfish owns that whole file, so it is rewritten outright.
//   - agents: the cross-provider AGENTS.md standard at ~/.codex/AGENTS.md
//     (read by Codex and other AGENTS.md consumers). Users often already have
//     one, so dotfish merges its content inside marker comments and leaves
//     everything outside them untouched.
package agentskill

import (
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/pamts/dotfiles-fish/internal/install"
	"github.com/pamts/dotfiles-fish/internal/manifest"
)

// Marker comments bounding the dotfish-owned region of a shared AGENTS.md.
const (
	beginMark = "<!-- BEGIN dotfish agent guide (generated by `dotfish agent`; edits inside are overwritten) -->"
	endMark   = "<!-- END dotfish agent guide -->"
)

// Run implements `dotfish agent`: resolve the Module subset, build the guide,
// and write it for each requested provider. docs is the embedded docs/modules
// tree (paths like docs/modules/eza.md).
func Run(man *manifest.Manifest, docs fs.FS, args []string) error {
	fset := flag.NewFlagSet("agent", flag.ContinueOnError)
	var providers string
	var all bool
	fset.StringVar(&providers, "providers", "claude,agents", "targets to write: claude, agents")
	fset.BoolVar(&all, "all", false, "include every Module, not just the installed subset")
	if err := fset.Parse(args); err != nil {
		return err
	}

	selected := man.Names()
	if !all {
		if inst := installedModules(man, install.FishDir()); len(inst) > 0 {
			selected = inst
		}
		// No snippets found means dotfish has not installed here yet (or Core
		// only): fall through with every Module so the guide is still useful.
	}

	sub, err := fs.Sub(docs, "docs/modules")
	if err != nil {
		return err
	}
	body := buildBody(man, sub, selected)

	for _, p := range strings.Split(providers, ",") {
		switch strings.TrimSpace(p) {
		case "":
		case "claude":
			path, err := claudePath()
			if err != nil {
				return err
			}
			if err := writeFile(path, claudeSkill(body)); err != nil {
				return err
			}
			fmt.Println("✓ Claude Code skill: " + path)
		case "agents":
			path, err := agentsPath()
			if err != nil {
				return err
			}
			if err := mergeAgentsFile(path, body); err != nil {
				return err
			}
			fmt.Println("✓ AGENTS.md (Codex & friends): " + path)
		default:
			return fmt.Errorf("unknown provider %q (want claude, agents)", p)
		}
	}
	return nil
}

// installedModules returns the Modules whose conf.d snippet is present in
// fishDir — the same inference install and the selector use to recognize a
// prior subset.
func installedModules(man *manifest.Manifest, fishDir string) []string {
	confd := filepath.Join(fishDir, "conf.d")
	var out []string
	for _, mod := range man.Modules {
		snip := mod.Snippet()
		if snip == "" {
			continue
		}
		if _, err := os.Stat(filepath.Join(confd, filepath.Base(snip))); err == nil {
			out = append(out, mod.Name)
		}
	}
	return out
}

// buildBody assembles the provider-neutral guide: a short framing for agents,
// then each selected Module's bundled usage doc with headings demoted one
// level so the guide reads as a single document.
func buildBody(man *manifest.Manifest, docs fs.FS, selected []string) string {
	var b strings.Builder
	b.WriteString(`# Fish shell on this machine — managed by dotfish

The fish configuration here is a Snapshot copy written by the dotfish
Installer: plain copies under ~/.config/fish, no symlinks. Direct edits there
are overwritten on the next dotfish run — machine-local changes belong in
~/.config/fish/profile.local.fish. Useful commands: ` + "`dotfish modules`" + `
(list Modules), ` + "`dotfish doctor`" + ` (verify the install),
` + "`dotfish upgrade`" + ` (move to the latest release).

The Modules below are installed on this machine. Several replace or wrap
common commands (ls, cat, grep, npm, ...) — consult the matching section
before scripting around a command that behaves unexpectedly.
`)
	for _, name := range selected {
		mod, ok := man.ByName(name)
		if !ok {
			continue
		}
		b.WriteString("\n")
		if doc, err := fs.ReadFile(docs, name+".md"); err == nil {
			b.WriteString(demote(string(doc)))
		} else {
			fmt.Fprintf(&b, "## %s — %s\n\nNo bundled guide for this Module.\n", mod.Name, mod.Description)
		}
	}
	b.WriteString("\n---\n\nRegenerate with `dotfish agent` after `dotfish upgrade` or after changing Modules.\n")
	return b.String()
}

// demote pushes every markdown heading down one level (# → ##) so a Module
// doc nests under the guide's own title. Lines inside fenced code blocks are
// left alone — fish comments start with # too.
func demote(md string) string {
	lines := strings.Split(md, "\n")
	inFence := false
	for i, ln := range lines {
		trimmed := strings.TrimLeft(ln, " \t")
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if !inFence && strings.HasPrefix(ln, "#") {
			lines[i] = "#" + ln
		}
	}
	return strings.Join(lines, "\n")
}

// claudeSkill wraps the guide in Claude Code skill frontmatter. The
// description is deliberately pushy about when to consult it: skills
// under-trigger, and the whole point is to be read before shell work.
func claudeSkill(body string) string {
	return `---
name: dotfish
description: Usage guide for this machine's fish shell, whose aliases, Wrappers, and environment are installed by the dotfish Installer. Consult this before running shell commands here, writing fish one-liners, or debugging why ls, cat, grep, npm, or another common command behaves unexpectedly — several are replaced by Modules on this machine.
---

` + body
}

func claudePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".claude", "skills", "dotfish", "SKILL.md"), nil
}

func agentsPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".codex", "AGENTS.md"), nil
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// mergeAgentsFile installs body between the dotfish markers in path,
// replacing a previous dotfish region but preserving everything the user
// keeps outside it. A missing file is created holding just the region.
func mergeAgentsFile(path, body string) error {
	region := beginMark + "\n\n" + body + "\n" + endMark
	existing, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return writeFile(path, region+"\n")
	}
	if err != nil {
		return err
	}
	text := string(existing)
	if i := strings.Index(text, beginMark); i >= 0 {
		if j := strings.Index(text, endMark); j > i {
			return writeFile(path, text[:i]+region+text[j+len(endMark):])
		}
		return fmt.Errorf("%s: found begin marker without end marker — fix the file and re-run", path)
	}
	if !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return writeFile(path, text+"\n"+region+"\n")
}
